---
name: ArcticKits
version: 1.0.1
api: 3.0.0
author: benzo
description: "Advanced kits plugin by benzo"
main: benzo\ArcticKits\Loader
commands:
  kits:
    description: "Open kit menu"
    permission: kit.cmd.use
    aliases: ["kit"]
permissions:
  kit.cmd.use:
    description: "Allows to use /kits command"
    default: true
depend:
- EconomyAPI

...