---
name: Kits
version: 1.0.1
api: 3.0.0
author: Kingbobs
description: "Advanced kits plugin"
main: Kit\Loader
commands:
  kits:
    description: "Open kit menu"
    permission: kit.cmd.use
    aliases: ["kit"]
permissions:
  kit.cmd.use:
    description: "Allows to use /kits command"
    default: true
depend:
- EconomyAPI

...
